paths:
  /products:
    get:
      summary: "Obtiene todos los productos"
      tags: 
        - Products
      responses:
        "200":
          description: "Los productos fueron obtenidos con exito"
        "500":
          description: "Error intentando acceder al listado de productos"
components:
  schemas:
    Products:
      type: object
      properties: 
        _id:
          type: ObjectId
          description: Id autogenerado por Mongo
        title:
          type: String
          description: Nombre del Producto
        description:
          type: String
          description: Descripcion del producto
        code:
          type: String
          description: Codigo referente al producto
        price:
          type: Number
          description: Precio del Producto
        thumbnail:
          type: String
          description: Link a la imagen del producto
        stock:
          type: Number
          description: Cantidad disponible del producto
        category:
          type: String
          description: Categoria a la que pertenece el producto 
        status:
          type: Boolean
          description: true
      example:
          _id: ObjectId("9962ff9a-4761-4cdf-b27e-961a7921406a")
          title: Lampara Tokio
          description: Lampara de pie con bombilla simple
          code: 9962ff9a-4761
          price: 12300
          thumbnail: Link a la imagen
          stock: 4
          category: Lampara de pie
          status: true 